name: CI Workflow for Spring Boot

on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때 실행
  pull_request:
    branches:
      - main  # 'main' 브랜치로 PR을 보낼 때 실행

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경은 Ubuntu 최신 버전

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Java 환경 설정 (Maven 사용 시 JDK 설치)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # JDK 버전 설정
          distribution: 'adoptopenjdk'  # JDK 배포판 설정

      # 3. Maven 캐시 설정 (빌드 시간 단축)
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository  # Maven의 로컬 저장소 경로
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # 캐시 키
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Maven 빌드 및 테스트 실행
      - name: Build and test with Maven
        run: mvn clean install -DskipTests  # 빌드 (테스트는 생략)

      # 5. 테스트 실행
      - name: Run tests with Maven
        run: mvn test  # 테스트 실행
        
      # 6. 빌드 결과 (선택 사항)
      - name: Build jar file
        run: mvn package  # 패키징
